name: unsup
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - seaborn
  - numpy
  - matplotlib
  - scikit-learn
  - scipy
  - pandas
  - jupyter
  - conda-forge::python-dotenv
  - scikit-bio
